package com.example.optimistic_lock.mapper;

import com.example.optimistic_lock.entity.TBalance;
import com.example.optimistic_lock.entity.TBalanceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    long countByExample(TBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    int deleteByExample(TBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    int insert(TBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    int insertSelective(TBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    List<TBalance> selectByExample(TBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    TBalance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBalance record, @Param("example") TBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBalance record, @Param("example") TBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBalance record);
}